<!DOCTYPE html>
<html>
	<head>
		<title>KuiRen Tour & Travel</title>
		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
		<link rel="icon" type="image/icon" href="<?=base_url('favicon.ico')?>">
		<script type="application/ld+json">
		{
		  "@context" : "http://schema.org",
		  "@type" : "LocalBusiness",
		  "name" : "KuiRen Tour",
		  "telephone" : [ "(+1) 234 56 789", "(+1) 234 56 780" ],
		  "email" : [ "", "" ],
		  "address" : {
		    "@type" : "PostalAddress",
		    "streetAddress" : "1100 High Street",
		    "addressLocality" : "New York City",
		    "addressCountry" : "USA"
		  }
		}
		</script>
		<!-- <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'> -->
		<link href="<?=base_url('assets/css/bootstrap.css?v1')?>" rel='stylesheet' type='text/css'/>
		<link href="<?=base_url('assets/css/web.css?v1.0')?>" rel="stylesheet" type="text/css" media="all"/>
		<link href="<?=base_url('assets/css/style.css?v12')?>" rel="stylesheet" type="text/css" media="all"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<script type="application/x-javascript"> 
			addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } 
		</script>
		<!--animated-css-->
		<link href="<?=base_url('assets/css/animate.css')?>" rel="stylesheet" type="text/css" media="all">
		<!--/animated-css-->
	</head>
	<body>
	<!--header-->
	<?php
	$this->load->view('_web/header');
	?>
	<!--About-->
	     <div class="about section" id="section-2">
			  <div class="container">
			  	<div class="row">
				  	<div class="col-md-8">
						<div class="about-head">
						  <h3 id="title" slug="<?=$tour_destination['tour_destination']->slug?>">
						  	<?=($tour_destination['tour_destination'])
						  	?$tour_destination['tour_destination']->title:'No title'?>
						  </h3>
						  <span></span>
						  <img lsrc="<?=base_url('assets/images/_web/star.png')?>" alt="">
						  <span style="width: 80%"></span>
						</div>
						<hr>
				  		<?=($tour_destination['tour_destination'])
				  			?$tour_destination['tour_destination']->content
				  			:'No Content';
				  		?>
				  	</div>
				  	<div class="col-md-4">
				  		<div class="about-head text-center">
						  <h3>
						  	Other Posts
						  </h3>
						  <span style="width: 30%"></span>
						  <img lsrc="<?=base_url('assets/images/_web/about-img.png')?>" alt="">
						  <span style="width: 40%"></span>
						</div>
						<div class="col-md-12" id="related_content">
<ul class="media-list">
  <li class="media">
    <div class="media-left">
      <a href="#">
        <img class="media-object" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PCEtLQpTb3VyY2UgVVJMOiBob2xkZXIuanMvNjR4NjQKQ3JlYXRlZCB3aXRoIEhvbGRlci5qcyAyLjYuMC4KTGVhcm4gbW9yZSBhdCBodHRwOi8vaG9sZGVyanMuY29tCihjKSAyMDEyLTIwMTUgSXZhbiBNYWxvcGluc2t5IC0gaHR0cDovL2ltc2t5LmNvCi0tPjxkZWZzPjxzdHlsZSB0eXBlPSJ0ZXh0L2NzcyI+PCFbQ0RBVEFbI2hvbGRlcl8xNTkzYWJjZjZlMSB0ZXh0IHsgZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQgfSBdXT48L3N0eWxlPjwvZGVmcz48ZyBpZD0iaG9sZGVyXzE1OTNhYmNmNmUxIj48cmVjdCB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIGZpbGw9IiNFRUVFRUUiLz48Zz48dGV4dCB4PSIxMi41NDY4NzUiIHk9IjM2LjUiPjY0eDY0PC90ZXh0PjwvZz48L2c+PC9zdmc+" alt="...">
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading">Media heading</h4>
      ...
    </div>
  </li>
</ul>						
						</div>
				  	</div>
			  	</div>
			  </div>
		</div>
		<hr>
	<!--/About-->
		<?php
		$this->load->view('_web/footer');
		?>
		<!--js--> 
		<script src="<?=base_url('assets/js/jquery.min.js?v12')?>"></script>
		<!--/js-->
		<script src="<?=base_url('assets/js/jquery-ui.min.js?v12')?>"></script>
		<script src="<?=base_url('assets/js/wow.min.js?v12')?>"></script>
		<script src="<?=base_url('assets/js/web_loader.js?v12')?>"></script>
		<script>
		 new WOW().init();
		</script>

		<script>
			$(document).ready(function(){
				/* loader init */
				var base_url = "<?=base_url()?>";
				var loader_url = "'"+base_url+"'";
				var delay = 3; // wait and then load the file
				var delayS = 5; // wait and then load the file
				setTimeout("loadDelayedScripts("+loader_url+")", delay * 1000);
				setTimeout("loadScript("+loader_url+")", delayS * 1000);
				/* end of loader sections */
				function get_related(){
					var except_slug = document.getElementById('title').getAttribute("slug");
					$.ajax({
						url : base_url + 'home/get_related_tour_destinations/' + except_slug + '/json',
						method : 'GET',
						success : function(r){
							sendToPage(r); /* call function */
						}
					}).done(function(r){
						console.info("done");
					});
				}

				function sendToPage(x){
					var jsonData = JSON.parse(x);
					for (var i = jsonData.length - 1; i >= 0; i--) {
						console.log(jsonData[i]);
					}
				}

				get_related();
			});
		</script>
	</body>
</html>