<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="author" content="Kuiren Tour And Travel">

	<?php
	echo favicon(); // header_helper
	$metas = (isset($metas))?$metas:null;
	generate_metas($metas); // header_helper

	?>

	<title>KuiRen Tour & Travel</title>
	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<?php
		echo google_json_ld(); // header_helper
	?>
	<link href="<?=base_url('assets/css/bootstrap.min.css');?>" rel="stylesheet" type="text/css" media="all"/>
	<link href="<?=base_url('assets/css/smart.css');?>" rel="stylesheet" type="text/css" media="all"/>
	<link href="<?=base_url('assets/css/style.css');?>" rel="stylesheet" type="text/css" media="all"/>
	<!--js-->
	<link type="text/css" rel="stylesheet" href="<?=base_url('assets/css/jquery.mmenu.all.css');?>" /> 	
	<!--/js-->
	<!--animated-css-->
	<link href="<?=base_url('assets/css/animate.css');?>" rel="stylesheet" type="text/css" media="all">
	<!--/animated-css-->
</head>
	<body>
	<!--header-->
	<?php
	$this->load->view('_smart/header');
	?>
	<!--About-->
	     <div class="about section" id="section-2">
			  <div class="container">
			  	<div class="row">
				  	<div class="col-md-8">
						<div class="about-head"><br>
						  <h3 id="title" slug="<?=$data->slug?>">
						  	<?=($data)
						  	?$data->title:'No title'?>
						  </h3>
						  <span></span>
						  <img lsrc="<?=base_url('assets/images/_smart/star.png')?>" alt="">
						  <span style="width: 74%"></span>
						</div>
						<br>
				  		<?=($data)
				  			?$data->content
				  			:'No Content';
				  		?>
				  		<div class="row" style="margin-top:50px" >
							<div class="col-md-12">
								<div class="about-head text-center">
								  <h4>
								  	Gallery Dari "<?=$data->title?>"
								  </h4>
								  <span style="width: 40%"></span>
								  <img lsrc="<?=base_url('assets/images/_web/about-img.png')?>" alt="">
								  <span style="width: 45%"></span>
								</div>
								<div id="portfoliolist">
								    <style>
								    	.custom-portofolio{
								    		display: inline-block; opacity: 1;
								    	}
								    </style>
											<?php
										if($gallery['images']):
										foreach($gallery['images'] as $img) { 
											?>
										<div class="portfolio card mix_all custom-portofolio" data-cat="card">
											<div class="portfolio-wrapper wow bounceIn" data-wow-delay="0.4s">		
												<a href="#" class="b-link-stripe b-animate-go  thickbox play-icon popup-with-zoom-anim">
											     	<img lsrc="<?=$img->image?>" alt="..." class="img-responsive" alt=""/>
													<div class="tour-caption" style="text-align:center">
														<span></span>
														<p>...</p>
													</div>
												</a>
											</div>
										</div>
											<?php
										}
										endif;
											?>
									   <div class="clearfix"></div>	
									</div>
							</div>
				  			<?php
				  			if(isset($display_form)){
					  			$this->load->view('templates/'.$display_form, 
					  				["default"=>(isset($default)?$default:null)]);
				  			}
				  			?>
				  		</div>
				  	</div>
				  	<div class="col-md-4" style="margin-top:30px">
				  		<div class="about-head text-center">
						  <h3>
						  	<?=isset($display_form)?(($display_form == 'request_car')?'Mobil Lainnya':'Tempat Lainnya'):'Pemandu Lainnya';?>
						  </h3>
						  <span style="width: 30%"></span>
						  <img lsrc="<?=base_url('assets/images/_web/about-img.png')?>" alt="">
						  <span style="width: 40%"></span>
						</div>
						<div class="col-md-12 col-xs-9" id="related_content" style="padding-top:20px">
							<ul class="media-list" id="otherPosts">

							</ul>						
						</div>
				  	</div>
			  	</div>
			  </div>
		</div>
		<hr>
	<!--/About-->
		<?php
		$this->load->view('_smart/footer');
		?>
		<!--js--> 
		<script src="<?=base_url('assets/js/jquery.min.js?v12')?>"></script>
		<!--/js-->
		<script src="<?=base_url('assets/js/jquery-ui.min.js?v12')?>"></script>
		<script src="<?=base_url('assets/js/smart_loader.js?v12')?>"></script>
		<script src="<?=base_url('assets/js/wow.min.js?v12')?>"></script>
		<script>

		$(document).ready(function(){
		 	new WOW().init();
			/* loader init */
			var base_url = "<?=base_url()?>";
			var loader_url = "'"+base_url+"'";
			var delay = 2; // wait and then load the file
			var delayS = 4; // wait and then load the file
			setTimeout("loadDelayedScripts("+loader_url+")", delay * 1000);
			setTimeout("loadScript("+loader_url+")", delayS * 1000);

			/* end of loader sections */
			function get_related(method){
				var except_slug = document.getElementById('title').getAttribute("slug");
				$.ajax({
					url : base_url + 'home/'+ method +'/' + except_slug + '/json',
					method : 'GET',
					success : function(r){
						sendToPage(r); /* call function */
					}
				}).done(function(r){
					//console.info("done");
				});
			}

			function sendToPage(x){
				var jsonData = JSON.parse(x);
				var template= function(t, l, c, i){
					var a = '<li class="media">\
						    <div class="media-body" style="width:75%;float:right;">\
						      <h4 class="media-heading">\
						      	<a href="'+ l +'">'+ t +'</a></h4>\
						      '+ c +'\
						    </div>\
						    <div class="media-left" style="width:70px">\
						      <a href="'+ l +'">\
						        <img class="media-object" width="50px" lsrc="' + i + '" alt="'+ l +'">\
						      </a>\
						    </div><hr>\
						  </li>';
					$('#otherPosts').append(a);
				}
				for (var i = jsonData.length - 1; i >= 0; i--) {
					var t = jsonData[i].title;
					var l = jsonData[i].slug;
					var c = jsonData[i].content + '...';
					c = c.replace(/<\/?[^>]+(>|$)/g, "");
					var img = jsonData[i].thumbnail;
					template(t, l, c, img);
				}
			}
			var method_selected= "<?=(isset($display_form))?(($display_form == 'request_tour')
								?'get_related_tour_destinations':'get_related_car'):'get_related_tour_guide'?>";
			get_related(method_selected);

		});
		</script>
			<?php
		if(isset($display_form)){
			?>

			<script src='https://www.google.com/recaptcha/api.js'></script>
			
			<?php
		}
			?>

	</body>
</html>